name: Actions workflow dispatch

on:
 workflow_dispatch:

jobs:
  run-git-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List of files
        run: |
          pwd
          ls
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo $GITHUB_REF_NAME
          echo '----GITHUB_TOKEN----'
          echo "${{ secrets.GITHUB_TOKEN }}"
          echo '----GH_TOKEN----'
          echo "${{ secrets.GITHUB_TOKEN }}"
